name: velocio
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  country_code_picker: ^3.0.0
  intl: ^0.18.1
  pinput: ^4.0.0
  
  

dev_dependencies:
  dart_code_metrics_presets: ^2.12.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0
  flutter_localizations:
    sdk: flutter


flutter:

  uses-material-design: true

  generate: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf

