name: velocio
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  country_code_picker: ^3.0.0
  intl: ^0.19.0
  pinput: ^4.0.0
  go_router: ^14.1.4
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.5.4
  logger: ^2.3.0
  email_validator: ^2.1.17
  intl_phone_number_input: ^0.7.4
  animated_snack_bar: ^0.4.0
  flutter_advanced_drawer: ^1.3.6
  flutter_svg: ^2.0.10+1
  # flutter_contacts: ^1.1.8
  rxdart: ^0.27.7
  # contacts_service: ^0.6.3
  permission_handler: ^11.3.1
  fast_contacts: ^3.1.3
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  webview_flutter: ^4.8.0
  local_auth: ^2.2.0
  lifecycle: ^0.8.0

dev_dependencies:
  dart_code_metrics_presets: ^2.12.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true

  generate: true

  assets:
    - .env
    - assets/vectors/
    - assets/illustrations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
